INSERT INTO questions (question, trial_id) VALUES ("Do you have a clinical diagnosis of Stargardts Macular Degeneration?", 1);
INSERT INTO questions (question, trial_id) VALUES ("What is your age?", 1);
INSERT INTO questions (question, trial_id) VALUES ("Are you able to give signed and dated written informed consent to participate in a clinical trial?", 1);
INSERT INTO questions (question, trial_id) VALUES ("Can you provide a genetic report indicating at least two ABCA4 disease-causing mutations? (When only one ABCA4 disease-causing mutation is reported, sponsor's permission will be required.)?", 1);
INSERT INTO questions (question, trial_id) VALUES ("Is at least one eye(called the "'primary study eye'") must have at least one well-demarcated area of significantly reduced autofluorescence as imaged by fundus autofluorescence(FAF)?", 1);
INSERT INTO questions (question, trial_id) VALUES ("Primary study eye must have clear ocular media and adequate pupillary dilation, including no allergy to dilating eyedrops, to permit good quality retinal imaging. Can you provide good quality retinal imaging?", 1);
INSERT INTO questions (question, trial_id) VALUES ("Some studies require you to be healthy as judged by an investigator. Do you feel you will pass this test?", 1);
INSERT INTO questions (question, trial_id) VALUES ("Are you able and willing to comply with study requirements, restrictions and instructions? For example, some studies are 24-month studies.", 1);
INSERT INTO questions (question, trial_id) VALUES (" Some studies require a female of childbearing potential to sign the informed consent about birth defects or attestation on contraception requirements. Are you able to sign informed consent?", 1);
INSERT INTO questions (question, trial_id) VALUES ("Do you have a clinical diagnosis of Stargardts Macular Degeneration?", 2);
INSERT INTO questions (question, trial_id) VALUES ("What is your age?", 2);
INSERT INTO questions (question, trial_id) VALUES ("Are you able to give signed and dated written informed consent to participate in a clinical trial?", 2);
INSERT INTO questions (question, trial_id) VALUES ("Some studies require Women of childbearing potential must have a negative pregnancy test at Day 1, and agree to use an effective form of contraception for at least three months, or be surgically sterile or postmenopausal, with the last menstrual period being over two years prior to enrollment. Select Yes if you will agree.", 2);
INSERT INTO questions (question, trial_id) VALUES ("Some studies require males to agree with their partner to use two forms of contraception for at least three months following SAR422459 administration. Select Yes if you will agree.", 2);
INSERT INTO questions (question, trial_id) VALUES ("If you will be enrolling in France, Are you affiliated to or benefit from a social security regimen?", 2);
INSERT INTO questions (question, trial_id) VALUES ("Is your Visual acuity ≤20/200 or ≤20/100 in the worst eye?", 2);
INSERT INTO questions (question, trial_id) VALUES (" Do you have Severe cone-rod dysfunction with no detectable or severely abnormal full-field electroretinogram responses?", 2);
INSERT INTO questions (question, trial_id) VALUES ("Do you have Abnormal full-field electroretinogram responses?", 2);
INSERT INTO questions (question, trial_id) VALUES ("Have you ever participated in an ocular gene transfer therapy study?", 2);
INSERT INTO questions (question, trial_id) VALUES ("Do you have a past medical history of human immunodeficiency virus (HIV) or hepatitis A, B, or C infection?", 2);
INSERT INTO questions (question, trial_id) VALUES ("Do you have a clinical diagnosis of Stargardts Macular Degeneration?", 3);
INSERT INTO questions (question, trial_id) VALUES ("What is your age?", 3);
INSERT INTO questions (question, trial_id) VALUES ("Are you able to give signed and dated written informed consent to participate in a clinical trial?", 3);
INSERT INTO questions (question, trial_id) VALUES ("Certain studies require that your disease not be effectively treated with conventional therapies. Are you not being effectively treated with conventional therapies?", 3);
INSERT INTO questions (question, trial_id) VALUES ("Is your best corrected visual acuity scores between 19 and 73 letter of the ETDRs (early treatment diabetic retinopathy ) eye chart, including 19 and 73, (or the equivalent of Snellen eyesight from 20/400 to 20/40)?", 3);
INSERT INTO questions (question, trial_id) VALUES ("Do you have visual loss caused by macular degeneration diseases?", 3);
INSERT INTO questions (question, trial_id) VALUES ("Do you have a clinical diagnosis of Stargardts Macular Degeneration?", 4);
INSERT INTO questions (question, trial_id) VALUES ("What is your age?", 4);
INSERT INTO questions (question, trial_id) VALUES ("Are you able to give signed and dated written informed consent to participate in a clinical trial?", 4);
INSERT INTO questions (question, trial_id) VALUES ("Have you been Diagnosed with an inherited retinal degenerative disease OR
are you Genetically-related to a person diagnosed with an inherited retinal degenerative disease?", 4);
INSERT INTO questions (question, trial_id) VALUES ("Do you have a clinical diagnosis of Stargardts Macular Degeneration?", 5);
INSERT INTO questions (question, trial_id) VALUES ("What is your age?", 5);
INSERT INTO questions (question, trial_id) VALUES ("Are you able to give signed and dated written informed consent to participate in a clinical trial?", 5);
INSERT INTO questions (question, trial_id) VALUES ("Do you have changes in pre-retinal media sufficient to obscure a view of the retina?", 5);
INSERT INTO questions (question, trial_id) VALUES ("Do you have a clinical diagnosis of Stargardts Macular Degeneration?", 6);
INSERT INTO questions (question, trial_id) VALUES ("What is your age?", 6);
INSERT INTO questions (question, trial_id) VALUES ("Are you able to give signed and dated written informed consent to participate in a clinical trial?", 6);
INSERT INTO questions (question, trial_id) VALUES ("Do you have a clinical diagnosis of Stargardts Macular Degeneration?", 7);
INSERT INTO questions (question, trial_id) VALUES ("What is your age?", 7);
INSERT INTO questions (question, trial_id) VALUES ("Are you able to give signed and dated written informed consent to participate in a clinical trial?", 7);
INSERT INTO questions (question, trial_id) VALUES ("Do you have less than or equal to 20/40 best corrected central visual acuity in one or both eyes AND/OR an abnormal visual field in one or both eyes?", 7);
INSERT INTO questions (question, trial_id) VALUES ("Have you been at least 3 months post-surgical treatment intended to treat any ophthalmologic disease AND are you stable?", 7);
INSERT INTO questions (question, trial_id) VALUES ("Are you under current medical therapy (pharmacologic treatment) for a retinal or optic nerve disease?", 7);
INSERT INTO questions (question, trial_id) VALUES ("Do you feel you have the potential for improvement with Bone Marrow Stem Cell treatment AND be at minimal risk of any potential harm from the procedure?", 7);
INSERT INTO questions (question, trial_id) VALUES ("Are you medically stable and able to be medically cleared by your primary care physician OR a licensed primary care practitioner for the procedure? (Medical clearance means that in the estimation of the primary care practitioner, the patient can reasonably be expected to undergo the procedure without significant medical risk to health.", 7);
INSERT INTO questions (question, trial_id) VALUES ("Do you have a clinical diagnosis of Stargardts Macular Degeneration?", 8);
INSERT INTO questions (question, trial_id) VALUES ("What is your age?", 8);
INSERT INTO questions (question, trial_id) VALUES ("Are you able to give signed and dated written informed consent to participate in a clinical trial?", 8);
INSERT INTO questions (question, trial_id) VALUES ("Participant must be able to cooperate with detailed psychophysics and electrophysiology testing. Are you able to do this?", 8);
INSERT INTO questions (question, trial_id) VALUES ("Participant must be able to provide a blood sample. Are you able to provide a blood sample?", 8);
INSERT INTO questions (question, trial_id) VALUES ("Do you have two (or more) clear mutations in the ABCA4 gene (ascertained with CLIA-certified testing) that are known to be associated with retinal disease OR one clear mutation in ABCA4 associated with a classic presentation of fundus flavimaculatus/Stargardt macular dystrophy (e.g., flecks, macular atrophy) OR one clear mutation in ABCA4, a cone-rod degeneration, AND no mutation in the ELOV4 or RDS genes?", 8);
INSERT INTO trials (status, name, interventions, url, min_age_req, max_age_req) VALUES ("recruiting", 'Phase 2 Tolerability and Effects of ALK-001 on Stargardts Disease', 'Drug: ALK-001|Drug: Placebo', 'https://ClinicalTrials.gov/show/NCT02402660', 12, 60);
INSERT INTO trials (status, name, interventions, url, min_age_req, max_age_req) VALUES ("recruiting", 'Phase I/IIa Study of SAR422459 in Patients With Stargardt\'s Macular Degeneration', 'Drug: SAR422459', 'https://ClinicalTrials.gov/show/NCT01367444', 6, 150);
INSERT INTO trials (status, name, interventions, url, min_age_req, max_age_req) VALUES ("recruiting", 'Clinical Study of Subretinal Transplantation of Human Embryo Stem Cell Derived Retinal Pigment Epitheliums in Treatment of Macular Degeneration Diseases', 'Procedure: Subretinal transplantation', 'https://ClinicalTrials.gov/show/NCT02749734', 18, 75);
INSERT INTO trials (status, name, interventions, url, min_age_req, max_age_req) VALUES ("recruiting", 'Inherited Retinal Degenerative Disease Registry Recruiting', 'No interventions', 'https://ClinicalTrials.gov/show/NCT02435940', 0, 150);
INSERT INTO trials (status, name, interventions, url, min_age_req, max_age_req) VALUES ("recruiting", 'Rod and Cone Mediated Function in Retinal Disease', 'Procedure: Subretinal transplantation', 'https://ClinicalTrials.gov/show/NCT02617966', 5, 150);
INSERT INTO trials (status, name, interventions, url, min_age_req, max_age_req) VALUES ("recruiting", 'High Resolution Retinal Imaging Recruiting', 'Procedure: Retinal imaging', 'https://ClinicalTrials.gov/show/NCT01866371', 7, 150);
INSERT INTO trials (status, name, interventions, url, min_age_req, max_age_req) VALUES ("recruiting", 'Stem Cell Ophthalmology Treatment Study', 'Procedure: IV (Intravenous)|Procedure: IVIT (Intravitreal)|Procedure: IO (Intraocular)', 'https://ClinicalTrials.gov/show/NCT01920867', 18, 150);
INSERT INTO trials (status, name, interventions, url, min_age_req, max_age_req) VALUES ("recruiting", 'Natural History of Eye Diseases Related to ABCA4 Mutations', 'Procedure: IV (Intravenous)|Procedure: IVIT (Intravitreal)|Procedure: IO (Intraocular)', 'https://ClinicalTrials.gov/show/NCT01736293', 12, 150);




